# Generated by Django 4.1.4 on 2023-01-07 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 14, 4, 12, 58720, tzinfo=datetime.timezone.utc)),
        ),
    ]
