# Generated by Django 4.1.4 on 2023-01-07 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 15, 22, 4, 899794, tzinfo=datetime.timezone.utc)),
        ),
    ]
