# Generated by Django 4.1.4 on 2023-01-07 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 19, 21, 39, 701934, tzinfo=datetime.timezone.utc)),
        ),
    ]
