# Generated by Django 4.1.4 on 2023-01-07 19:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_bio_alter_user_email_alter_user_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='You should write +996[code][number]', regex='^(\\+996)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 19, 45, 40, 248812, tzinfo=datetime.timezone.utc)),
        ),
    ]
