# Generated by Django 4.1.4 on 2023-01-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_chatroom_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='name',
            new_name='name_owner',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name_reciever',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
