# Generated by Django 4.1.4 on 2023-01-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_rename_name_chatroom_name_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
